import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import { sanityClient, urlFor } from "../sanity";
import { Post } from "../typing";
import Link from "next/link";

interface Props {
  posts: [Post];
}

export default function Home({ posts }: Props) {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Meduim Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="flex justify-center items-center bg-gray-200 border-y border-black py-10 lg:p-0">
        <div className="px-10 space-y-5 ">
          <h1 className="md:text-5xl max-w-xl font-serif text-2xl">
            <span className=" decoration- decoration-4">
              Skyelip International LTD
            </span>
          </h1>
          <h2>
            an independent financial advisory company that provides well rounded
            solutions.
          </h2>
        </div>
        <div>
          <img
            className="hidden md:inline-flex h-32 lg:h-full py-30 mt-10 mb-10"
            src="https://res.cloudinary.com/dgfdgi5hf/image/upload/v1665779217/logo-removebg-preview_ir3zme.png"
            alt="logo"
          />
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 p-2 md:p-6">
        {posts.map((post) => (
          <Link href={`/post/${post.slug.current}`} key={post._id}>
            <div className="border rounded-lg shadow-lg group cursor-pointer overflow-hidden">
              <img
                className="h-60 w-full object-cover group-hover:scale-105 transition-transform duration-200 ease-in-out"
                src={urlFor(post.mainImage).url()!}
                alt=""
              />
              <div className="flex justify-between p-5 bg-white">
                <div>
                  <p className="text-lg font-bold">{post.title}</p>
                  <p className="text-xs">
                    {post.description}   by {post.author.name}
                  </p>
                </div>
                <img
                  className="h-12 w-12 rounded-full border-2 border-[#AC49BA]"
                  src={urlFor(post.author.image).url()!}
                  alt=""
                />
              </div>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `
      *[_type == "post"] {
        _id,
        title,
        author -> {
           name,
           image
        },
        description,
        mainImage, 
        slug
      }
    `;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};
